runtime: nodejs18
service: doodle-fish-api
instance_class: F1

automatic_scaling:
  min_instances: 1
  max_instances: 4
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75
  max_idle_instances: 2
  min_idle_instances: 1


handlers:
- url: /.*
  script: auto

health_check:
  enable_health_check: True
  check_interval_sec: 20
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2